#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id

#-------------------------------
# Google Font URL
google_font_url: "https://fonts.googleapis.com/css2?family=Saira:ital,wght@0,100..900;1,100..900&display=swap"
google_font_family: "Saira"